# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGWbttagP9IP1nPidMh5sX5UE1LhRbnD
"""

# install all required libraries
import time
import requests
from requests.exceptions import ConnectionError, HTTPError
from requests.auth import HTTPBasicAuth
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
import os
import logging
from typing import Dict, Any, Optional
#from google.colab import userdata
from dotenv import load_dotenv
#from .custom_exceptions import GitHubAPIError, ResourceNotFound

#api_token = userdata.get('GithubAPI_token')
#"repository_url": "https://api.github.com/repos/{owner}/{repo}"

class gitHubClient:
    '''A resilient client for interacting with the GitHub API.'''
    load_dotenv()

    api_token = os.getenv("GITHUB_TOKEN")

    session = requests.Session()

    #max_retries = Retry(
       #total=5,
       #backoff_factor=0.1,
       #status_forcelist=[429, 500, 502, 503, 504]
      #)

    max_retries = 3


    def __init__(self, base_url="https://api.github.com/"):
         self.base_url = base_url


    def _make_request(self, method: str, endpoint: str) -> Dict[str, Any]:
        """Makes an API request with automatic retries for rate limits."""
        # TODO: Implement the retry logic here (exponential backoff)
        url = self.base_url + endpoint

        logging.info(f"making and API request from {url}")
        try:
            session = requests.Session()
            session.headers.update(self._get_headers())
            #response = session.request(method, url)
            for attempt in range(gitHubClient.max_retries):
                      response = session.get(url)
                      response.raise_for_status()

                      if response.status_code == 200:
                                    return response.json()

                      print(f"Error {response.status_code}, retrying…")
                      time.sleep(1.5 * (attempt + 1))  # simple backoff

            raise Exception("Max retries exceeded")

        except requests.exceptions.RequestException as e:
            logging.error(f"API request failed: {e}")


    def _get_headers(self) -> Dict[str, str]:
        """Constructs the headers for API requests."""
        # TODO: Construct auth headers
        # The headers parameter in the original function signature was not used, and the token needs to be formatted as a string.
        return {
            'Authorization': f'Bearer {gitHubClient.api_token}',
            'Accept': 'application/json'
        }

    def get_repo_details(self, owner: str, repo: str) -> Dict[str, Any]:
        """Fetches details for a specific repository."""
        # TODO: Call _make_request to fetch repo info
        endpoint = f"/repos/{owner}/{repo}"    # e.g /repos/python/cpython
        # url = self.base_url + endpoint # _make_request will handle constructing the full URL

        return self._make_request("GET", endpoint)

    def get_user(self, user_url: str) -> dict:
         """Fetches a single user by their ID."""
         endpoint = f"/users/{user_url}"

         return self._make_request("GET", endpoint)

    def get_user_by_id(self, user_id: int) -> dict:
         """Fetches a single user by their ID."""
         endpoint = f"/users/{user_id}"
         #url = self.base_url + endpoint

         return self._make_request("GET", endpoint)

    def get_rate_limit(self) -> dict:
         """Fetches a single user by their ID."""
         endpoint = "/rate_limit"
         #url = self.base_url + endpoint

         return self._make_request("GET", endpoint)

#testing the client
client = gitHubClient()     # Create an instance of the client before calling its methods
results = client.get_repo_details("python", "cpython")

print(results)